name: sparky
description: Sparky é pacote que ajuda na construção de apis rest de forma simples com suporte a websocket a autenticação jwt.
version: 1.2.0
repository: https://github.com/viniciusddrft/Sparky
homepage: https://github.com/viniciusddrft/Sparky

topics:
  - sparky
  - server
  - api
  - backend

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
