name: sparky
description: Sparky é pacote que ajuda na construção de apis rest de forma simples com suporte a websocket a autenticação jwt.
version: 1.0.1
repository: https://github.com/viniciusddrft/Sparky
homepage: https://github.com/viniciusddrft/Sparky

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
